print("Hello, World!")
print("This is a simple Python script.")
print("My name is Kabir.")
print ("I am learning Python programming.")
print("I enjoy solving problems and building projects.")
print("Python is a versatile language used in various fields.")
print("I am excited to continue my journey in Python programming.")
print("I hope to create useful applications and contribute to the community.")
print("I am grateful for the resources and support available for learning Python.")
print("I will keep practicing and improving my skills.")
print("I am looking forward to collaborating with other developers and sharing knowledge.")
print("I am committed to writing clean and efficient code.")
print("I am also a master a Mathamatics and I love to solve problems." )
print("5 + 5 = ", 5 + 5)
print("Thank you for reading my script!")